# Generated by Django 3.2.15 on 2022-10-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0003_auto_20221004_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_supperuser',
            new_name='is_superuser',
        ),
    ]
