# Generated by Django 3.2.15 on 2022-10-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0005_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_delete',
        ),
    ]
