# Generated by Django 3.2.15 on 2022-10-04 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0007_auto_20221004_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_start', models.DateField(null=True)),
                ('max_person', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('location', models.CharField(max_length=255)),
                ('create_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_person', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, choices=[('01', 'physics'), ('02', 'chemistry'), ('03', 'biology'), ('04', 'math'), ('05', 'literature')], max_length=3, null=True)),
                ('max_person', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
