# Generated by Django 3.2.16 on 2022-10-04 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0009_auto_20221004_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truong',
            name='create_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
