# Generated by Django 3.2.15 on 2022-10-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0011_auto_20221005_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoa',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lop',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='truong',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
