# Generated by Django 3.2.15 on 2022-10-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0012_auto_20221005_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoa',
            name='shool',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shool_app.truong'),
        ),
        migrations.AddField(
            model_name='lop',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shool_app.khoa'),
        ),
    ]
