# Generated by Django 3.2.15 on 2022-10-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0014_studentclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='Lop',
            new_name='classname',
        ),
    ]
