# Generated by Django 3.2.15 on 2022-10-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0015_rename_lop_studentclass_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
