# Generated by Django 3.2.15 on 2022-10-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shool_app', '0016_alter_studentclass_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='StudentManagement',
        ),
    ]
